/* Generated by Yosys 0.30+48 (git sha1 b5b0b7e83, x86_64-w64-mingw32-g++ 13.1.0 -march=nocona -msahf -mtune=generic -O2 -Os) */

(* top =  1  *)
(* src = "celda_tipica.v:1.1-28.10" *)
module Tipica_DI(n, A, B, N);
  (* src = "celda_tipica.v:5.15-5.16" *)
  input A;
  wire A;
  (* src = "celda_tipica.v:5.18-5.19" *)
  input B;
  wire B;
  (* src = "celda_tipica.v:6.13-6.14" *)
  output N;
  wire N;
  (* src = "celda_tipica.v:5.12-5.13" *)
  input n;
  wire n;
  (* src = "celda_tipica.v:8.6-8.10" *)
  wire notA;
  (* src = "celda_tipica.v:8.12-8.14" *)
  wire s0;
  (* src = "celda_tipica.v:8.16-8.18" *)
  wire s1;
  (* src = "celda_tipica.v:8.20-8.22" *)
  wire s2;
  assign notA = ~(* src = "celda_tipica.v:0.0-0.0" *) A;
  assign s1 = notA |(* src = "celda_tipica.v:12.4-13.17" *)  B;
  assign s0 = notA &(* src = "celda_tipica.v:14.5-15.17" *)  B;
  assign s2 = n &(* src = "celda_tipica.v:16.5-17.15" *)  s1;
  assign N = s2 |(* src = "celda_tipica.v:18.4-19.16" *)  s0;
endmodule
