/* Generated by Yosys 0.30+48 (git sha1 b5b0b7e83, x86_64-w64-mingw32-g++ 13.1.0 -march=nocona -msahf -mtune=generic -O2 -Os) */

(* top =  1  *)
(* src = "celda_inicial.v:1.1-9.10" *)
module Inicial_DI(A, B, N);
  (* src = "celda_inicial.v:7.12-7.14" *)
  wire _0_;
  (* src = "celda_inicial.v:4.12-4.13" *)
  input A;
  wire A;
  (* src = "celda_inicial.v:4.14-4.15" *)
  input B;
  wire B;
  (* src = "celda_inicial.v:5.13-5.14" *)
  output N;
  wire N;
  assign _0_ = ~(* src = "celda_inicial.v:7.12-7.14" *) A;
  assign N = _0_ |(* src = "celda_inicial.v:7.12-7.18" *)  B;
endmodule
